[package]
name = "dioxus-tui-sample"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = "0.2.4"
dioxus-html = "0.2.1"
dioxus-tui = "0.2.2"
tokio = "1.24.2"
